# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eheart/server/proto/response.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from eheart.server.proto import util_pb2 as eheart_dot_server_dot_proto_dot_util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"eheart/server/proto/response.proto\x12\x06\x65heart\x1a\x1e\x65heart/server/proto/util.proto\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x13\x44iffvarNameResponse\x12\r\n\x05names\x18\x01 \x03(\t\"*\n\x12\x43urrentValResponse\x12\t\n\x01t\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x03(\x01\"\x85\x01\n\x10SolutionResponse\x12\x1e\n\x01t\x18\x01 \x01(\x0b\x32\x13.eheart.ValueSeries\x12%\n\x08\x64iffvars\x18\x02 \x03(\x0b\x32\x13.eheart.ValueSeries\x12*\n\rwatching_vars\x18\x03 \x03(\x0b\x32\x13.eheart.ValueSeries\"\x1d\n\x0bValueSeries\x12\x0e\n\x06values\x18\x01 \x03(\x01\"$\n\x12ValueArrayResponse\x12\x0e\n\x06values\x18\x01 \x03(\x01\"J\n\x14MethodReturnResponse\x12\x32\n\x0creturn_value\x18\x01 \x03(\x0b\x32\x1c.eheart.GenericScalarOrArrayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eheart.server.proto.response_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSRESPONSE._serialized_start=78
  _STATUSRESPONSE._serialized_end=128
  _DIFFVARNAMERESPONSE._serialized_start=130
  _DIFFVARNAMERESPONSE._serialized_end=166
  _CURRENTVALRESPONSE._serialized_start=168
  _CURRENTVALRESPONSE._serialized_end=210
  _SOLUTIONRESPONSE._serialized_start=213
  _SOLUTIONRESPONSE._serialized_end=346
  _VALUESERIES._serialized_start=348
  _VALUESERIES._serialized_end=377
  _VALUEARRAYRESPONSE._serialized_start=379
  _VALUEARRAYRESPONSE._serialized_end=415
  _METHODRETURNRESPONSE._serialized_start=417
  _METHODRETURNRESPONSE._serialized_end=491
# @@protoc_insertion_point(module_scope)
