# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eheart/server/eheart.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from eheart.server.proto import util_pb2 as eheart_dot_server_dot_proto_dot_util__pb2
from eheart.server.proto import request_pb2 as eheart_dot_server_dot_proto_dot_request__pb2
from eheart.server.proto import response_pb2 as eheart_dot_server_dot_proto_dot_response__pb2

from eheart.server.proto.util_pb2 import *
from eheart.server.proto.request_pb2 import *
from eheart.server.proto.response_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65heart/server/eheart.proto\x12\x06\x65heart\x1a\x1e\x65heart/server/proto/util.proto\x1a!eheart/server/proto/request.proto\x1a\"eheart/server/proto/response.protoP\x00P\x01P\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eheart.server.eheart_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
